# Generated by Django 4.1 on 2022-09-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Amounts',
        ),
    ]
