# Generated by Django 4.1 on 2022-09-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amounts',
        ),
    ]
