# Generated by Django 4.1 on 2022-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0004_delete_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_nm_eng', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('account_nm_kor', models.CharField(max_length=255)),
                ('stock_code', models.CharField(max_length=20)),
                ('fs_div', models.CharField(max_length=20)),
                ('sj_div', models.CharField(max_length=20)),
                ('Q202211013', models.FloatField(blank=True, default=None, null=True)),
                ('Q202111011', models.FloatField(blank=True, default=None, null=True)),
                ('Q202111014', models.FloatField(blank=True, default=None, null=True)),
                ('Q202111012', models.FloatField(blank=True, default=None, null=True)),
                ('Q202111013', models.FloatField(blank=True, default=None, null=True)),
                ('Q202011011', models.FloatField(blank=True, default=None, null=True)),
                ('Q202011014', models.FloatField(blank=True, default=None, null=True)),
                ('Q202011012', models.FloatField(blank=True, default=None, null=True)),
                ('Q202011013', models.FloatField(blank=True, default=None, null=True)),
                ('Q201911011', models.FloatField(blank=True, default=None, null=True)),
                ('Q201911014', models.FloatField(blank=True, default=None, null=True)),
                ('Q201911012', models.FloatField(blank=True, default=None, null=True)),
                ('Q201911013', models.FloatField(blank=True, default=None, null=True)),
                ('Q201811011', models.FloatField(blank=True, default=None, null=True)),
                ('Q201811014', models.FloatField(blank=True, default=None, null=True)),
                ('Q201811012', models.FloatField(blank=True, default=None, null=True)),
                ('Q201811013', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
