# Generated by Django 4.1.1 on 2022-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dart", "0005_amounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ratios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=20)),
                ("ratio", models.CharField(max_length=255)),
                ("Q202211013", models.FloatField(blank=True, default=None, null=True)),
                ("Q202111011", models.FloatField(blank=True, default=None, null=True)),
                ("Q202111014", models.FloatField(blank=True, default=None, null=True)),
                ("Q202111012", models.FloatField(blank=True, default=None, null=True)),
                ("Q202111013", models.FloatField(blank=True, default=None, null=True)),
                ("Q202011011", models.FloatField(blank=True, default=None, null=True)),
                ("Q202011014", models.FloatField(blank=True, default=None, null=True)),
                ("Q202011012", models.FloatField(blank=True, default=None, null=True)),
                ("Q202011013", models.FloatField(blank=True, default=None, null=True)),
                ("Q201911011", models.FloatField(blank=True, default=None, null=True)),
                ("Q201911014", models.FloatField(blank=True, default=None, null=True)),
                ("Q201911012", models.FloatField(blank=True, default=None, null=True)),
                ("Q201911013", models.FloatField(blank=True, default=None, null=True)),
                ("Q201811011", models.FloatField(blank=True, default=None, null=True)),
                ("Q201811014", models.FloatField(blank=True, default=None, null=True)),
                ("Q201811012", models.FloatField(blank=True, default=None, null=True)),
                ("Q201811013", models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
