# Generated by Django 4.1.1 on 2022-09-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dart", "0006_ratios"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=20)),
                ("stock_name", models.CharField(max_length=255)),
            ],
        ),
    ]
