# Generated by Django 4.1.1 on 2022-10-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dart", "0007_stocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="amounts",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="close",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="high",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="low",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="market",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="stocks",
            name="market_cap",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="open",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="shares",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="volume",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
