# Generated by Django 4.1.1 on 2022-10-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dart", "0008_stocks_amounts_stocks_close_stocks_high_stocks_low_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
